CC	= gcc
CFLAGS  = -g3 -Wall -Werror -Wextra -pedantic
FILENAME = strace

strace_0: 0-strace.c
	$(CC) $(CFLAGS) 0-strace.c -o $(FILENAME)_0

strace_1: 1-strace.c
	$(CC) $(CFLAGS) 1-strace.c -o $(FILENAME)_1

strace_2: 2-strace.c
	$(CC) $(CFLAGS) 2-strace.c -o $(FILENAME)_2

strace_3: 3-strace.c print_out.c
	$(CC) $(CFLAGS) 3-strace.c print_out.c -o $(FILENAME)_3
